### ISSUE TITLE
"TypeError: Cannot read property 'value' of null" on ESLint 3.16.0

### ISSUE THREAD

**Issue by wyze** [gajus/eslint-plugin-flowtype#196]
When upgrading ESLint to the latest version, this plugin now throws these errors. You can see this for yourself when upgrading the version of ESLint in the `devDependencies` of this package.

```
  1) space-after-type-colon valid type X = (number) => string;:
     TypeError: Cannot read property 'value' of null
      at src/rules/typeColonSpacing/reporter.js:20:9

  2) space-after-type-colon valid type X = (number) => string;:
     TypeError: Cannot read property 'value' of null
      at src/rules/typeColonSpacing/reporter.js:20:9

  3) space-before-type-colon valid type X = (number) => string;:
     TypeError: Cannot read property 'value' of null
      at src/rules/typeColonSpacing/reporter.js:20:9

  4) space-before-type-colon valid type X = (number) => string;:
     TypeError: Cannot read property 'value' of null
      at src/rules/typeColonSpacing/reporter.js:20:9
```

I'll have a PR that fixes this shortly.

**Comment by RusAlex** [comment]
Suffering from the same issue.
