### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined at EventEmitter.GenericTypeAnnotation

### ISSUE THREAD

**Issue by unlight** [gajus/eslint-plugin-flowtype#234]
https://astexplorer.net/#/gist/7658ea195b58bd931ffd4328a55072fd/33418e26d7a74552fceb758e6faeddbd925b6952
```
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

export class AppState {

    loggedIn: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
}
```

```
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.GenericTypeAnnotation (~\node_modules\eslint-plugin-flowtype\dist\rules\useFlowType.js:38:40)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (~\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (~\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (~\node_modules\eslint\lib\util\node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (~\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (~\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Traverser.enter (~\node_modules\eslint\lib\eslint.js:929:36)
    at Traverser.__execute (~\node_modules\estraverse\estraverse.js:397:31)
    at Traverser.traverse (~\node_modules\estraverse\estraverse.js:501:28)
```
```
      for (scope = context.getScope(); scope; scope = scope.upper) {

        variable = scope.set.get(typeId.name); // <--------
        if (variable && variable.defs.length) {
          context.markVariableAsUsed(typeId.name);
          break;
        }
      }
```

**Comment by gajus** [comment]
Cannot replicate. Likely already fixed.
