### ISSUE TITLE
Cannot read property 'kind' of null

### ISSUE THREAD

**Issue by leaves4j** [gajus/eslint-plugin-flowtype#241]
js file:
```js
//@flow

interface ITest  {
  name: string;
  run(): void;
}

class Test implements ITest {
  name: string;
  run(): void {}
}
```
.eslintrc
```json
{
  
  "parser": "babel-eslint",
  "plugins": [
    "flowtype"
  ],
  "extends": [
    "plugin:flowtype/recommended"
  ]
}
```
package.json:
```json
{
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.0.0",
    "eslint-plugin-flowtype": "^2.34.0",
    "flow-bin": "^0.48.0",
    "flow-remove-types": "^1.2.1"
  }
}
```

errors:
```shell
Cannot read property 'kind' of null
TypeError: Cannot read property 'kind' of null
    at shouldBeStatically (/Users/xxxxxx/node_modules/eslint-scope/lib/scope.js:149:54)
    at Array.every (native)
    at GlobalScope.__shouldStaticallyCloseForGlobal (/Users/xxxxxx/node_modules/eslint-scope/lib/scope.js:2
91:40)
    at GlobalScope.__globalCloseRef (/Users/xxxxxx/node_modules/eslint-scope/lib/scope.js:315:18)
    at GlobalScope.__close (/Users/xxxxxx/node_modules/eslint-scope/lib/scope.js:337:22)
    at GlobalScope.__close (/Users/xxxxxx/node_modules/eslint-scope/lib/scope.js:559:22)
    at Referencer.close (/Users/xxxxxx/node_modules/eslint-scope/lib/referencer.js:129:68)
    at Referencer.Program (/Users/xxxxxx/node_modules/eslint-scope/lib/referencer.js:450:14)
    at Referencer.Visitor.visit (/Users/xxxxxx/node_modules/esrecurse/esrecurse.js:122:34)
    at Object.analyze (/Users/xxxxxx/node_modules/eslint-scope/lib/index.js:138:16)
```

**Comment by gajus** [comment]
That looks like an issue with https://github.com/eslint/eslint-scope

**Comment by gajus** [comment]
Closing as stale.
