### ISSUE TITLE
TypeError: Error while loading rule 'flowtype/boolean-style': cb is not a function

### ISSUE THREAD

**Issue by lll000111** [gajus/eslint-plugin-flowtype#254]
Plugin version 2.35.0
eslint version 4.2.0

```
TypeError: Error while loading rule 'flowtype/boolean-style': cb is not a function

TypeError: Error while loading rule 'flowtype/boolean-style': cb is not a function
    at Object.exports.default (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint-plugin-flowtype\dist\utilities\checkFlowFileAnnotation.js:24:10)
    at apply (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint-plugin-flowtype\node_modules\lodash\lodash.js:496:27)
    at Object.wrapper [as create] (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint-plugin-flowtype\node_modules\lodash\lodash.js:5356:16)
    at Object.keys.filter.forEach.key (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\linter.js:871:67)
    at Array.forEach (native)
    at Linter.verify (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\linter.js:844:93)
    at processText (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:203:31)
    at CLIEngine.executeOnText (C:\Users\mha\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:668:26)
    at ESLintPlugin.getErrors (C:\Program Files\JetBrains\WebStorm 171.4073.15\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:83:32)
    at ESLintPlugin.onMessage (C:\Program Files\JetBrains\WebStorm 171.4073.15\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint-plugin.js:42:33)
Process finished with exit code -1
```

When I remove `"plugin:flowtype/recommended"` from `extends: [...]` in `.eslintrc.js` the error disappears.

**Comment by jfirebaugh** [comment]
I had the same problem. It was due to a stale WebStorm child process. Restarting WebStorm resolved the issue.

**Comment by tribou** [comment]
I had this issue while using `eslint_d`. `eslint_d stop && eslint_d start` fixed it for me.
