### ISSUE TITLE
error Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by StevePotter** [gajus/eslint-plugin-flowtype#293]
Hi, we are using version 2.39.1 and I suddenly got an error when creating a Flow type from spreading other types.  This is a feature of Flow that allows union types for sealed objects.  Without the spread syntax, I cannot get Flow to work right.  So Flow worked but then lint failed.

It fails on all of the eslint-flowtype rules.  Only if I remove them from .eslintrc.json does it work.  Disabling all the rules in a /* eslint-disable */ did not fix it.

The Flow type that's causing it:
```
type DataProps = {
  ...ApolloQueryResult,
  ...ClaimsQuery,
  refetch: () => Promise<Object>,
  loadMoreClaims: () => Promise<Object>,
}
```

Stack trace:
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at /private/tmp/mobile/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:76:31
    at arrayEach (/private/tmp/mobile/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/private/tmp/mobile/node_modules/lodash/lodash.js:9359:14)
    at checkForDuplicates (/private/tmp/mobile/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:73:22)
    at listeners.(anonymous function).forEach.listener (/private/tmp/mobile/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/private/tmp/mobile/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/private/tmp/mobile/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/private/tmp/mobile/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/private/tmp/mobile/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/private/tmp/mobile/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

I assume this is a Flow feature that hasn't been taken into account.  I'd be happy to work on a fix.  Any tips for getting started?

**Comment by valentinvoilean** [comment]
Any news about this issue ?

**Comment by serchavalos** [comment]
This is happening to me too. Any news?

**Comment by StevePotter** [comment]
@gajus I can help.  Maybe on the first try we should just guard against the crash.  How about that?

**Comment by StevePotter** [comment]
PR #302 submitted.  Thanks

**Comment by IanVS** [comment]
It seems there have been a few PRs submitted to try to fix this bug, but none of them have been merged.  I've resorted to adding files to my `.eslintignore` to avoid this bug in the few places where I spread flow types, but that's a really scary thing to do.  @gajus what kind of a PR would you accept at this point in order to fix this bug?

**Comment by gajus** [comment]
> It seems there have been a few PRs submitted to try to fix this bug [..]

The main reason the existing PRs have not been merged is because they simply ignore the issue.

I would accept a PR that uses the latest version of babel/ babel-eslint.

**Comment by MoOx** [comment]
@gajus Maybe you should close those PR with this explanation (a PR closed doesn't mean "it's dead", it's just a cleanup ^^)

**Comment by IanVS** [comment]
I believe this is now fixed in recent versions, possibly by https://github.com/gajus/eslint-plugin-flowtype/pull/325.  I think the issue can be closed.

**Comment by gajus** [comment]
Thank you @IanVS
