### ISSUE TITLE
Error with eslint@4.14.0

### ISSUE THREAD

**Issue by Manjiz** [gajus/eslint-plugin-flowtype#296]
``` bash
> eslint jsbundles/

Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isForInRef (**/node_modules/eslint/lib/rules/no-unused-vars.js:410:23)
    at variable.references.some.ref (**/node_modules/eslint/lib/rules/no-unused-vars.js:447:21)
    at Array.some (<anonymous>)
    at isUsedVariable (**/node_modules/eslint/lib/rules/no-unused-vars.js:446:40)
    at collectUnusedVariables (**/node_modules/eslint/lib/rules/no-unused-vars.js:569:26)
    at Program:exit (**/node_modules/eslint/lib/rules/no-unused-vars.js:621:36)
    at listeners.(anonymous function).forEach.listener (**/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (**/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (**/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

I can't track the position of this error.

Fixed with eslint@4.12.1

**Comment by motevets** [comment]
We confirmed that this works with 4.13.0 but not with 4.14.0.

**Comment by fabiopaiva-innovactory** [comment]
https://github.com/eslint/eslint/issues/9767#issuecomment-353840674
