### ISSUE TITLE
Support Importing Types for Private Properties

### ISSUE THREAD

**Issue by bradennapier** [gajus/eslint-plugin-flowtype#371]
It would appear that there is a bug causing imported types to not work when used on private properties.

https://github.com/bradennapier/repro-eslint-flowtype-import-bug

The repro above reproduces the issue.  It ends up showing the bug within `no-unused-vars` but the bug is clearly a flowtype issue.

The issue only happens when using `import type`

**update** just noticed this actually occurs if you use any imported value at all.

**Comment by gajus** [comment]
What is the input and what is the error?

**Comment by bradennapier** [comment]
The repro shows it clearly.  

```
[Error - 10:44:23 AM] TypeError: Cannot read property 'type' of undefined
    at isForInRef (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:430:24)
    at variable.references.some.ref (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:467:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:466:40)
    at collectUnusedVariables (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:578:26)
    at collectUnusedVariables (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:585:17)
    at Program:exit (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/rules/no-unused-vars.js:630:36)
    at listeners.(anonymous function).forEach.listener (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Shared/Development/projects/repros/babel-eslint-type-undefined/node_modules/eslint/lib/util/safe-emitter.js:45:38)

```
